version: '3'
services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: digitalocean.com/php
    container_name: php
    restart: unless-stopped
    tty: true
    ports:
      - "6101:6001"
      - "9111:9111"
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network
    depends_on:
      - nginx
      - redis
      - mysql

  #Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8585:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - network

  #Redis Service
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    volumes:
      - ./docker/redis:/data
    ports:
      - "6389:6379"
    networks:
      - network

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_ROOT_PASSWORD: main_root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
